
version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  chroma:
    image: chromadb/chroma:0.4.24
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./chroma_data:/data

  pdf-summary-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - chroma
    volumes:
      - ./uploads:/app/uploads

volumes:
  redis-data:
  chroma_data:

