version: "3.8"

services:
  app:
    build: .
    container_name: ucware-app
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - chroma
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE

